### ISSUE TITLE
ElasticSearch TimeoutException 개선

### ISSUE THREAD

**Issue by hoa0217** [f-lab-edu/modoospace#56]
<img width="542" alt="스크린샷 2024-03-20 오후 11 29 22" src="https://github.com/f-lab-edu/modoospace/assets/48192141/fb428fed-e7a3-4379-997f-bb754e9ccebf">

ES를 사용할 때가 쿼리를 사용할 때 보다 TPS가 약 3배 높은 상황(처리량 3배, 지연시간1/3). 하지만 에러응답이 187개가 왔기때문에 이를 개선해보고자함. 서버에선 아래와 같이 ElasticSearch와 통신하려다 TimeOutException이 발생하였으므로  2가지 방법을 시도해볼 것.

```bash
2024-03-20 21:57:01.581 ERROR 1 --- [o-8080-exec-834] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: error while performing request] with root cause

java.util.concurrent.TimeoutException: Connection lease request time out
	at org.apache.http.nio.pool.AbstractNIOConnPool.processPendingRequest(AbstractNIOConnPool.java:411) ~[httpcore-nio-4.4.16.jar!/:4.4.16]
	at org.apache.http.nio.pool.AbstractNIOConnPool.processNextPendingRequest(AbstractNIOConnPool.java:391) ~[httpcore-nio-4.4.16.jar!/:4.4.16]
	at org.apache.http.nio.pool.AbstractNIOConnPool.release(AbstractNIOConnPool.java:355) ~[httpcore-nio-4.4.16.jar!/:4.4.16]
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.releaseConnection(PoolingNHttpClientConnectionManager.java:393) ~[httpasyncclient-4.1.5.jar!/:4.1.5]
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.releaseConnection(AbstractClientExchangeHandler.java:247) ~[httpasyncclient-4.1.5.jar!/:4.1.5]
	at org.apache.http.impl.nio.client.MainClientExec.responseCompleted(MainClientExec.java:387) ~[httpasyncclient-4.1.5.jar!/:4.1.5]
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:173) ~[httpasyncclient-4.1.5.jar!/:4.1.5]
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448) ~[httpcore-nio-4.4.16.jar!/:4.4.16]
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338) ~[httpcore-nio-4.4.16.jar!/:4.4.16]
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) ~[httpcore-nio-4.4.16.jar!/:4.4.16]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:87) ~[httpasyncclient-4.1.5.jar!/:4.1.5]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:40) ~[httpasyncclient-4.1.5.jar!/:4.1.5]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) ~[httpcore-nio-4.4.16.jar!/:4.4.16]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[httpcore-nio-4.4.16.jar!/:4.4.16]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[httpcore-nio-4.4.16.jar!/:4.4.16]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio-4.4.16.jar!/:4.4.16]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio-4.4.16.jar!/:4.4.16]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.16.jar!/:4.4.16]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[httpcore-nio-4.4.16.jar!/:4.4.16]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

```

---

- [x] TimeOut 시간 늘리기 1-> 10

> 외부 네트워크 환경에서 Elasticsearch와 통신할 경우, 네트워크 지연이나 변동성이 내부 네트워크보다 크게 증가할 수 있습니다. 이런 환경에서는 연결 타임아웃(Connection Timeout)과 소켓 타임아웃(Socket Timeout)을 조금 더 넉넉하게 설정하는 것이 좋습니다.
연결 타임아웃: 연결 타임아웃은 서버에 연결을 시도할 때까지의 시간입니다. 외부 네트워크 환경에서는 5초보다 더 긴 시간이 필요할 수 있습니다. 일반적으로 10초에서 20초 사이로 설정하는 것이 안전 마진을 제공하고, 네트워크 지연으로 인한 연결 실패를 줄일 수 있습니다.
출처: gpt
 
- [x] 커넥션풀 늘리기 `MaxConnTotal` 20 -> 100, `MaxConnPerRoute` 2 -> 50

> 성능테스트에서 가상User수를 200명으로 가정했으므로 ElasticSearch 동시 접속자 수는 1/4인 50명으로 잡음.
> 참고: https://hc.apache.org/httpcomponents-asyncclient-4.1.x/current/httpasyncclient/apidocs/org/apache/http/impl/nio/conn/PoolingNHttpClientConnectionManager.html

**Comment by hoa0217** [comment]
timeout 10으로 바꾸고 Error 187 -> 25
<img width="247" alt="스크린샷 2024-03-21 오전 1 11 08" src="https://github.com/f-lab-edu/modoospace/assets/48192141/cef83e52-d485-4757-92c0-d54539cd0267">

**Comment by hoa0217** [comment]
참고: https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/7.17/_basic_authentication.html

**Comment by hoa0217** [comment]
Max Connection 50으로 늘리고 에러 0 달성 👍
<img width="242" alt="스크린샷 2024-03-21 오전 2 33 29" src="https://github.com/f-lab-edu/modoospace/assets/48192141/752cbef2-3a39-4cfe-948b-7dbca210a218">
